[project]
name = "botcode"
version = "0.1.0"
description = "A simple bot for _____"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keyboard>=0.13.5",
    "pillow>=11.0.0",
    "pyautogui>=0.9.54",
]
